---
apiVersion: v1
kind: Service
metadata:
  name: thanos-compact-headless
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: compact
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 10902
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: compact
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compact
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: compact
spec:
  serviceName: thanos-compact-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: compact
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        app.kubernetes.io/component: compact
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.40.1
          imagePullPolicy: IfNotPresent
          args:
            - compact
            - --log.level=info
            - --log.format=logfmt
            - --http-address=0.0.0.0:10902
            - --data-dir=/var/thanos/compact
            - --objstore.config-file=/etc/thanos/objstore.yaml
            - --wait
            - --retention.resolution-raw=90d
            - --retention.resolution-5m=180d
            - --retention.resolution-1h=365d
            - --delete-delay=48h
            - --compact.concurrency=1
            - --downsample.concurrency=1
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/thanos/compact
            - name: objstore-config
              mountPath: /etc/thanos/objstore.yaml
              subPath: objstore.yaml
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-objstore-secret
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
