---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 10902
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: query-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        app.kubernetes.io/component: query-frontend
    spec:
      serviceAccountName: workload-identity-sa
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.41.0
          imagePullPolicy: IfNotPresent
          args:
            - query-frontend
            - --log.level=info
            - --log.format=logfmt
            - --http-address=0.0.0.0:10902
            - --query-frontend.downstream-url=http://thanos-query.thanos.svc.cluster.local:10902
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
