---
apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-router
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive-router
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 10902
      targetPort: http
      protocol: TCP
    - name: remote-write
      port: 19291
      targetPort: remote-write
      protocol: TCP
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-receive-router
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: receive-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        app.kubernetes.io/component: receive-router
    spec:
      serviceAccountName: workload-identity-sa
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.41.0
          imagePullPolicy: IfNotPresent
          args:
            - receive
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --remote-write.address=0.0.0.0:19291
            - --receive.replication-factor=1
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention=6h
            - --label=receive="true"
            - --label=replica="$(POD_NAME)"
            - --receive.hashrings-file=/etc/thanos/hashrings.json
            - --receive.local-endpoint=$(POD_NAME).thanos-receive-ingestor-headless.$(NAMESPACE).svc.cluster.local:10901
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: remote-write
              containerPort: 19291
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/thanos
            - name: hashring-config
              mountPath: /etc/thanos/hashrings.json
              subPath: hashrings.json
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
        - name: data
          emptyDir: {}
        - name: hashring-config
          configMap:
            name: thanos-receive-hashring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-hashring
  namespace: thanos
data:
  hashrings.json: |
    [
      {
        "hashring": "default",
        "tenants": [],
        "endpoints": [
          "thanos-receive-ingestor-0.thanos-receive-ingestor-headless.thanos.svc.cluster.local:10901",
          "thanos-receive-ingestor-1.thanos-receive-ingestor-headless.thanos.svc.cluster.local:10901"
        ]
      }
    ]
