apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: thanos
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: "1.22.x"
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: thanos
      interval: 12h
      reconcileStrategy: ChartVersion
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: thanos-values
      valuesKey: values.yaml
