---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway-headless
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: store-gateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 10902
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: store-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: thanos
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: store-gateway
spec:
  serviceName: thanos-store-gateway-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: store-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        app.kubernetes.io/component: store-gateway
    spec:
      serviceAccountName: workload-identity-sa
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.40.1
          imagePullPolicy: IfNotPresent
          args:
            - store
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --data-dir=/var/thanos/store
            - --objstore.config-file=/etc/thanos/objstore.yaml
          ports:
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: http
              containerPort: 10902
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/thanos/store
            - name: objstore-config
              mountPath: /etc/thanos/objstore.yaml
              subPath: objstore.yaml
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-objstore-secret
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
