apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Qh9byi56ltZldOgj+J2mDj3LqMBilqr1cnNmt9Ax5lKtgtccDKCocw==,iv:XLgc6t6wzPfHy4m+Ew4EbaDiWrdqb2HF0SK6/JM7oh0=,tag:ORjqj0I163ZAm0ixHAySnA==,type:str]
sops:
    age:
        - recipient: age1efeu9sg7e84dq2x0sku52vdvfsmttjazdj390jkrpmr4gd3tg4psldtdsh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNENERWlqSUJ3eXZ1TTdh
            QnlBcXJXVGowKzZiWDd5ZTVWZm1DZy9zSVhRCk9ydGZsZXVhZURJYjF6aWw5L3lH
            Mk8rQ3B0b3hOSEIxWEsyVTJNc3dMNHcKLS0tIDdtVmFiUHR0ektXa3R3NmNuSk5U
            S3ErRTBWbkduSmZGT0gwR0c2d3FUYWMKgiUssoJazVMdsZdtqQK41z2zoRzHp3qc
            WkRyDm0QF9zGq6/K2PQugnxvkKvw51KEWvHVAxvIRXyfYIW9fzE9zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T19:06:13Z"
    mac: ENC[AES256_GCM,data:4US3z4lSQuFhrGo2AGiv/0eS1dr6od0caOa86CtNaWsz7tL0f/nLjEwEZu0/aZKIF9lKQfZUlv+DBIyhki/d15Hn0VvQJT5HE9W+nzJgW8fsdeSnOciekaQUBS6gAIR1XNk0ntHCLnBwq2HD0Y3T/LBWDhAgTX6+MSU465ucTxw=,iv:qc/9g9nqOzs4+mjLk2UNhFeF8wLrZx+gsebU/x0hFqI=,tag:UQqYBDaZ1o5m19DYB1of3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
