apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 12h
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: promtail-loki-credentials
      valuesKey: username
      targetPath: config.clients[0].basic_auth.username
    - kind: Secret
      name: promtail-loki-credentials
      valuesKey: password
      targetPath: config.clients[0].basic_auth.password
  values:
    config:
      # Promtail server configuration
      server:
        http_listen_port: 3101
        grpc_listen_port: 9095
        log_level: info

      # Loki clients configuration
      clients:
        - url: https://loki-gateway.cloudandklir.com/loki/api/v1/push
          tenant_id: "1"
          basic_auth:
            username: ""  # Populated from valuesFrom
            password: ""  # Populated from valuesFrom
          tls_config:
            insecure_skip_verify: false

      # Positions file to track what has been read
      positions:
        filename: /run/promtail/positions.yaml

      # Target discovery configuration
      scrape_configs:
        # Scrape Kubernetes pod logs
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod

          pipeline_stages:
            # Extract metadata from CRI format logs (containerd/cri-o)
            - cri: {}

            # Drop logs from specific namespaces (reduce storage costs)
            # Note: kube-public and kube-node-lease are low-value namespaces
            - drop:
                source: namespace
                expression: "(kube-public|kube-node-lease)"
                drop_counter_reason: "excluded_namespace"

          relabel_configs:
            # Only scrape running pods
            - source_labels:
                - __meta_kubernetes_pod_phase
              regex: Pending|Succeeded|Failed|Completed
              action: drop

            # Add namespace label
            - source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace

            # Add pod name label
            - source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod

            # Add container name label
            - source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container

            # Add app label if exists
            - source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app

            # Add job label from app.kubernetes.io/name if exists
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: job

            # Set path to read logs from
            - source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
              separator: /
              replacement: /var/log/pods/*$1/*.log

    # DaemonSet configuration - run on every node
    daemonset:
      enabled: true

    # Resource limits
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

    # SecurityContext - run as root to read log files, but without privileged mode
    securityContext:
      runAsUser: 0
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    # Tolerations to run on all nodes including control plane
    tolerations:
      - effect: NoSchedule
        operator: Exists

    # ServiceMonitor for Prometheus metrics
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
