apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: linkding
spec:
    refreshPolicy: CreatedOnce
    refreshInterval: "0"
    secretStoreRef:
        name: azure-key-vault-store
        kind: ClusterSecretStore
    target:
        name: cloudflare-tunnel-credentials # The Kubernetes Secret that will get created (in the "linkding" namespace)
        creationPolicy: Owner
    data:
        - secretKey: "credentials.json" # The name of the key within the Kubernetes Secret
          remoteRef:
              key: linkding-k3s-qa # The name of the secret in Azure Key Vault
