apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: workload-identity-webhook
  namespace: workload-identity
spec:
  interval: 30m
  chart:
    spec:
      chart: workload-identity-webhook
      version: "1.5.x"
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: workload-identity
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
