apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:66iHShW1RDEkEHf5mGOAbFfB1AZp/7VDrEMsaiXIoBm5yJXiDzZD6TUSdtEbZFFZdXj1vBsxHTtcf2Ds4t3bvLQypiaLeYmoSl1BIMIeOTs5Z1hFIe3Zw/WVCCbM28UNBffKgHyn/n/EC1snci+f8lNzOgc0uityc5rceZFH6N/5hccNgcvXHj1cDup47OTQyCWAyyGDK1ENRZVjHuZ0WSy0hic7Idkn4hZJVGI8rkDpnA5lDJHUPX9sOoQy4T75x6l5zH31rXomq07uLzMBaDaTJzAwxooLAAAc9a9rVOalYMJF38tbhru90zo=,iv:8A54uCnZljvZ+dwOzt53NT/es7yKvbqTDhXpIIQeSZU=,tag:Z6ncm2OELI/kewxgZCq/LA==,type:str]
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age1efeu9sg7e84dq2x0sku52vdvfsmttjazdj390jkrpmr4gd3tg4psldtdsh
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WVR5ZUZJZEs2MzQrSXI5
              NFFNR2Jrbng2ODVjRTVVR2xhM1U0YnJoUHpjCnVwYjZ3RVQ5WjNLNWxxR3JGRDVL
              NVc0c1cvUkxKUlRGSkpOMXBvTE1EWnMKLS0tIGwvZUgzR3VhMlZxK2pZVTNJL0hW
              emJlbi9VWUVlanQ4Q2tidjgxMHhIdDQK96qOQH1ETSiX8HGwi2Bgq82ki6goImxZ
              Z6NODvx9ILVBVPfQCI/2s+7m0EdZNIFR2rAuXqSuYrYflx9hPlY9VQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T11:09:10Z"
    mac: ENC[AES256_GCM,data:JCMt6BKV5wcxJE7fIN9IMz8kQMKghoaUN24VORELPMUD35ygWfquE1a04DqBnJmbHfl4e71THXSnh0FeQKkhizusbA7YJrcbF5ZjMNn6wwZxJnw8S7Fn4+WdVt6YG0/UQBJa4a7JjngGx4mPBPdiUXMZntSP2tDcBIgxH+HBzoY=,iv:MfGXFU7+lICjfz/M6CQ/ep0EZYg9AZzx2BWeTLVPLs0=,tag:SzD8IoxbyrfjMB2MjQjZDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
