apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:COoCyUEEjjg50Z9iWpDKoddlBAzXuMBVSeenTtQ52/nRQoKaqkRjLJp/3As2/PsuoYMPlKQM+HOMwZChVXm5XRvOlWafqPF0PO1XrVo+zhOyg8SPCUmlzJbATovv9ZgPqcxE8wZPuYaeTUNRcVSsOmw0qto/CTXFrdya4J0y6xDjgGEs66smrsc6Ebi67kt/Y3P+mtmMPLpJ/LY9tH2p3S0Y6Ib8p5MdLejFV6l3gGD8MFfAveyyQ+cCAzzCImeKaZ5V+1o6dkhsKp5oRfWhq8UVqD0Qu80U,iv:0XNwPRbW6UN8GkzGMh0/F8ju7nhFsVuLRfED22YCVJE=,tag:DuT92SGNSBf/bpoQZl3fLA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-tunnel-cred
    namespace: linkding
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1efeu9sg7e84dq2x0sku52vdvfsmttjazdj390jkrpmr4gd3tg4psldtdsh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUWF5WCtiWDVXTHA3c1pP
            dTE5bkNacDFJOFZOUngxWXViR3NKQzdTejJNClhRS0Z2SUwydjRIUERlaXg4eWhj
            SXBhSDdmZ0dPTXF1Y2NZK0JjVkM0RW8KLS0tIENkZ1hkUzk0Q2RCTnVPWVQydy9z
            Nmp0ZUYzS1g4QlI3UGZtZ1VSSWg3NE0KpyPTPqv1i/PHTXrns/WLtGzw5PO4VcUJ
            TQ0BoxV4ei8QL0cIEebV6owROuzf2U60h0cT4ykugZ7jEcl3aKmUKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:29:13Z"
    mac: ENC[AES256_GCM,data:BoN8z8CsMd8poZh3rk4YgOWj6frEhImx0fr0IYPcGn0iDGLoUmrC7gYbbNesmuC6RtY+6T37gQ7SOLpSEpT5u4w7+n3IZ1yXsVdAMxb3vggMphscZrX2DHFtOe3E5X4ILkIjo/+vbA4rlmoguOYiMPNibQ2f8+0QBln2S+EnjOM=,iv:/BWB7oZB7MTgYArosiWxOuxOUMT/SlitwCDnVXjDLs0=,tag:gG4QJBPwWRrUwoesLJdxuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
