apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  # dependsOn:                  # An optional list used to refer to other Kustomization objects that the Kustomization depends on.
  #   - name: infra-configs     # If specified, then the Kustomization is only applied after the referred Kustomizations are ready, i.e. have the Ready condition marked as True
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
