#!/bin/bash

# Provisioning the VM Template

while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo "Waiting for cloud-init..."; sleep 1; done
sudo systemctl enable qemu-guest-agent
sudo systemctl start qemu-guest-agent
sudo cloud-init clean
sudo rm -f /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
sudo rm -f /etc/netplan/00-installer-config.yaml
echo "Ubuntu Server 24.04 LTS Template by Packer - Creation Time: $(date)" | sudo tee /etc/issue
