apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid # Prevent overlapping cronjob runs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - maor-klir/homelab-k8s-cluster
              envFrom:
                - secretRef:
                    name: renovate-github-token
                - configMapRef:
                    name: renovate-configmap
          restartPolicy: Never
